@baseURL=http://localhost:8080

### New user
POST  {{baseURL}}/users/login
Content-Type: application/json

{
    "email": "andres@iniesta.com",
    "password": "xavi"
}

### New user
POST  {{baseURL}}/users
Content-Type: application/json

{
    "email": "andres@iniesta.com",
    "password": "xavi123"
}